job_index:
    path:     /
    defaults: { _controller: "EnsManonBundle:Job:index" }
    methods:  GET

job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsManonBundle:Job:show" }
    requirements:
        id:  \d+
    methods:  GET

job_preview:
    path:  /{company}/{location}/{token}/{position}
    defaults: { _controller: "EnsManonBundle:Job:preview" }
    requirements:
        token:  \w+

job_new:
    path:     /new
    defaults: { _controller: "EnsManonBundle:Job:new" }
    methods:  [GET, POST]

job_create:
    path:     /create
    defaults: { _controller: "EnsManonBundle:Job:create" }
    methods:  POST

job_edit:
    path:  /{token}/edit
    defaults: { _controller: "EnsManonBundle:Job:edit" }

job_update:
    path:  /{token}/update
    defaults: { _controller: "EnsManonBundle:Job:update" }
    methods:  POST

job_delete:
    path:  /{token}/delete
    defaults: { _controller: "EnsManonBundle:Job:delete" }
    methods:  POST

job_publish:
    path:  /{token}/publish
    defaults: { _controller: "EnsManonBundle:Job:publish" }
    methods:  POST