job_index:
    path:     /
    defaults: { _controller: "EnsManonBundle:Job:index" }
    methods:  GET

job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsManonBundle:Job:show" }
    requirements:
        id:  \d+
    methods:  GET

job_new:
    path:     /new
    defaults: { _controller: "EnsManonBundle:Job:new" }
    methods:  [GET, POST]

job_create:
    path:     /create
    defaults: { _controller: "EnsManonBundle:Job:create" }
    methods:  POST

job_edit:
    path:     /{id}/edit
    defaults: { _controller: "EnsManonBundle:Job:edit" }

job_update:
    path:     /{id}/update
    defaults: { _controller: "EnsManonBundle:Job:update" }
    methods:  POST

job_delete:
    path:     /{id}/delete
    defaults: { _controller: "EnsManonBundle:Job:delete" }
    methods:  POST